Basic ZooKeeper Operator implementation
stackabletech/zookeeper-operator pull request #12
Opened 2020-12-19 23:02 UTC by lfrancke

2020-12-22 22:31 UTC, lfrancke commented
This does not yet compile because some changes in operator-rs are missing.
There are also _a lot of things_ that I know are still bad but I still believe now would be a good time for a first review.

2021-01-08 15:12 UTC, soenkeliebau reviewed
Not fully done yet, I'll continue next week but wanted to post the first comments.

2021-01-08 15:12 UTC, soenkeliebau commented on operator/src/lib.rs
> +fn build_containers(
I've not reviewed most of this, as it will substantially change in the future I expect.

2021-01-13 09:55 UTC, soenkeliebau requested changes
I'll finish the review for now. We are still discussing the overall approach to reconciliation.

2021-01-18 12:44 UTC, lfrancke commented on crd/src/lib.rs
> +    const CRD_DEFINITION: &'static str = r#"
This is _hopefully_ fixed in a new version of kube-rs. They added support for generating these schemas. I haven't looked into it yet.

2021-01-19 15:11 UTC, lfrancke commented on server/src/main.rs
> +        stackable_operator::create_client(Some("zookeeper.stackable.de".to_string())).await?;
Yes, but I can't reuse other constants in a const definition because ` calls in constants are limited to constant functions, tuple structs and tuple variants`

```
error[E0015]: calls in constants are limited to constant functions, tuple structs and tuple variants
  --> operator/src/lib.rs:32:31
   |
32 | const FINALIZER_NAME: &str = &format!("{}/cleanup", GROUP_NAME);
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

2021-01-19 15:18 UTC, lfrancke commented on operator/src/lib.rs
> +    used_ids.sort_unstable();
That's a good point. I need to check for duplicates above. In that case this `sort_unstable` should be fine.

2021-01-19 15:27 UTC, lfrancke commented on operator/src/lib.rs
> +                used_ids.push(added_id);
I think you're right. I added another sort after the push but this whole thing seems fragile (and should almost certainly be moved to a function)

2021-01-19 15:33 UTC, lfrancke commented on operator/src/lib.rs
> +            context.client.delete(&pod).await?;
Good point. No, it doesn't.

2021-01-19 15:36 UTC, lfrancke commented on crd/src/lib.rs
> +            serde_json::json!(self.version).as_str().unwrap()
No, I think this can never fail. I didn't find a better way of converting the enums.

2021-01-19 15:37 UTC, lfrancke commented on operator/src/lib.rs
> +async fn create_pod(
I agree. This is painful to look at. I had one big method to begin with and I refactored it. Now I almost liked the earlier version better. I'm not sure how to do this better yet.

2021-01-19 15:38 UTC, lfrancke commented on operator/src/lib.rs
> +async fn add_finalizer(context: &ZooKeeperReconcileContext) -> ZooKeeperReconcileResult {
Yes, this will move to the operator framework

2021-01-19 15:38 UTC, lfrancke commented on operator/src/lib.rs
> +async fn handle_deletion(context: &ZooKeeperReconcileContext) -> ZooKeeperReconcileResult {
Yes, this will move to the operator framework

2021-01-21 16:08 UTC, lfrancke commented on server/src/main.rs
> +        stackable_operator::create_client(Some("zookeeper.stackable.de".to_string())).await?;
I just found out about the `const_concat` crate which we could pull in for this. I don't think it's worth it but happy to do if you like.

2021-01-21 16:09 UTC, lfrancke commented on crd/src/lib.rs
> +    const CRD_DEFINITION: &'static str = r#"
I'd like to get this merged first (and the operator-rs changes) before I upgrade the kube-rs dependency. I'll resolve this for now.

2021-01-21 16:10 UTC, lfrancke commented on crd/src/lib.rs
> +                      enum: [ 3.4.13, 3.4.14 ]
I'll resolve this for now because it should hopefully be fixed by the kube-rs stuff (but probably won't)

2021-01-28 10:50 UTC, lfrancke commented on operator/src/lib.rs
> +    // * check if a pod is up but not running/ready yet, skip the remaining reconciliation if this is the case
At the moment, yes. I'll add a TODO.

2021-01-28 12:26 UTC, lfrancke commented
Build fails because it now relies on https://github.com/stackabletech/operator-rs/pull/41

2021-01-29 14:38 UTC, lfrancke commented on operator/src/lib.rs
> +async fn create_pod(
I've changed it a bit. We can change it further but I think it's a bit better.

2021-01-29 14:47 UTC, lfrancke commented on operator/src/lib.rs
> +        .render("conf", &json!({ "options": options }))
Uhm... I don't fully understand which variables could be undefined?

I'm almost certain I don't want to ignore undefined variables so I'd like to fix it :)

2021-02-03 13:55 UTC, soenkeliebau requested changes
I've been through large parts of the code and left a few comments. In its current form the code doesn't work, mainly due to pod naming issues and an accidental deletion of a shared value (see comments).
That being said, Lars mentioned, that he already has a few changes lined up that make parts of the code I mentioned as broken obsolete.
I'll leave it up to Lars how to proceed with this PR - merge in its current (minus the bugs) form or update it directly.

2021-02-03 13:55 UTC, soenkeliebau commented on operator/src/lib.rs
> +            .ok_or(error::Error::ReconcileError("foobar".to_string()))?;
This code seems to do the same as earlier code, which is retrieve a mutable reference to id_information, but looks totally different.
Also, replace with proper error message.

And to round things of, I keep hitting the error condition here, something seems to be off with your usage of RefCell, it looks like the content keeps vanishing between the function calls..

2021-02-03 13:55 UTC, soenkeliebau commented on operator/src/lib.rs
> +            .take()
.take() removes the inner value from the RefCell and replaces it with Default::default() which causes issues in delete_excess_pods which needs the remaining servers from that struct.

2021-02-04 13:31 UTC, lfrancke commented
I believe I fixed all issues. But this should not currently build because it relies on two PRs from operator rs

https://github.com/stackabletech/operator-rs/issues/49
https://github.com/stackabletech/operator-rs/issues/46

2021-02-06 00:31 UTC, soenkeliebau approved these changes
LGTM
I've built the operator and ran it with two agents, everything worked as expected.

Comments are also addressed as far as can be expected.

2021-02-06 20:14 UTC, merged