Enable monitoring
stackabletech/zookeeper-operator pull request #146
Opened 2021-07-20 13:17 UTC by maltesander

- Added metrics port to CR
- Added ENV variable for javaagent to start jmx exporter

2021-07-20 13:55 UTC, razvan reviewed
Some suggestions

2021-07-20 13:55 UTC, razvan commented on deploy/config-spec/properties.yaml
> +        unit: *unitPort
```suggestion
        unit: *unitPort
        min: "1024"
        max: "65535"
```

2021-07-20 13:55 UTC, razvan commented on deploy/config-spec/properties.yaml
> +      description: "The port where ZooKeeper metrics are exposed."
```suggestion
      description: "The port where ZooKeeper metrics are exposed as a Prometheus endpoint."
      
```

2021-07-20 13:55 UTC, razvan commented on operator/src/lib.rs
> +                                            "{{", "}}", version.package_name(), port,  "{{", "}}", version.package_name())),
```suggestion
                                value: Some(format!("-javaagent:{{{{packageroot}}}}/{}/stackable/lib/jmx_prometheus_javaagent-0.16.1.jar={}:{{{{packageroot}}}}/{}/stackable/conf/jmx_exporter.yaml",
                                             version.package_name(), port,  version.package_name())),
```

2021-07-26 08:14 UTC, siegfriedweber requested changes

2021-07-26 08:14 UTC, siegfriedweber commented on crd/src/lib.rs
> +            result.insert("metricsPort".to_string(), Some(metrics_port.to_string()));
Set `SERVER_JVMFLAGS` already here and remove the section from `create_pod_and_config_maps`.

2021-07-26 08:14 UTC, siegfriedweber commented on operator/src/lib.rs
> +            );
`clientPort` could also be added to the container ports.

2021-07-27 07:32 UTC, maltesander commented on crd/src/lib.rs
> +            result.insert("metricsPort".to_string(), Some(metrics_port.to_string()));
Im checking it right now. The problem here is that we would not check that "metricsPort" via the product-config if we add it here. But in general yeah, the `create_pod_and_config_maps` is a monster, it needs to be splitted.

2021-07-27 07:37 UTC, maltesander commented on operator/src/lib.rs
> +            );
Done.

2021-07-27 13:38 UTC, siegfriedweber approved these changes
LGTM

2021-07-27 13:42 UTC, merged