Added runAsUser configuration property.
stackabletech/zookeeper-operator pull request #172
Opened 2021-08-24 14:02 UTC by razvan

## Description

Added `runAsUser` configuration property to the service configuration. If present, it will set the desired user name in the pod's security context.

Depends on https://github.com/stackabletech/operator-rs/pull/200.

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)

2021-08-24 16:01 UTC, razvan commented
One problem with this seems to be that the `ConfigMap` files belong to `root`:
```
root@f1fb00307a4b:/agent# ls -l /tmp/zookeeper/
total 4
-rw-r--r-- 1 root root 1 Aug 24 15:47 myid
root@f1fb00307a4b:/agent# ls -l /tmp/ | grep zookeeper
drwxr-xr-x 2 root      root      4096 Aug 24 15:47 zookeeper
root@f1fb00307a4b:/agent# 
```

and therefore the service cannot start:

```
Aug 24 15:47:11 f1fb00307a4b zkServer.sh[710]: 2021-08-24 15:47:11,795 [myid:1] - ERROR [main:ZooKeeperServerMain@75] - Unable to access datadir, exiting abnormally
Aug 24 15:47:11 f1fb00307a4b zkServer.sh[710]: org.apache.zookeeper.server.persistence.FileTxnSnapLog$DatadirException: Unable to create data directory /tmp/zookeeper/version-2
``

2021-08-30 09:34 UTC, lfrancke requested changes

2021-08-30 09:34 UTC, lfrancke commented on deploy/config-spec/properties.yaml
> +        - value: "/var/log/stackable/servicelogs"
Hmmm is this correct?
Doesn't this also need a zookeeper subdirectory?

2021-08-30 09:34 UTC, lfrancke commented on deploy/config-spec/properties.yaml
> +      description: "The port where ZooKeeper metrics are exposed as a Prometheus endpoint."
Wrong docs

2021-08-30 09:34 UTC, lfrancke commented on operator/src/lib.rs
> +        let security_context = run_as_user.map_or(PodSecurityContextBuilder::new().build(), |u| {
Is the default correct for us? Before we had none here and now we use a default one. Is that a difference?

2021-08-31 07:48 UTC, razvan commented
Since this functionality is not supported by the Stackable agent I will close this PR but keep the branch for future reference.

2021-08-31 07:48 UTC, closed without merging