Operator rework ("STFU")
stackabletech/zookeeper-operator pull request #263
Opened 2021-11-15 10:52 UTC by teozkr

## Description

This is the first operator rework according to the STFU prototype discussed earlier.

This first draft removes support for product-config, but the plan is to reintroduce support for this.

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

2021-11-19 14:30 UTC, maltesander reviewed
Ok im through. Checked the code and tested it, works fine. I think we have 2 approaches here:

1) Merge as is and go from there (i think @soenkeliebau prefers that)
2) Merge this in a developer branch, adapt 1 or 2 more operators (e.g. opa, kafka) and start refactoring and testing already (which i would prefer)

Im good with both, my reasoning for option 2 is that we now have way more operators than when we started with the old framework (which in term need to be adapted whenever we refactor, so i would prefer a "solid" basis for shared code over iterating through everything again and again)

2021-11-23 15:07 UTC, lfrancke requested changes

2021-11-23 15:07 UTC, lfrancke commented on rust/operator-binary/src/znode_controller.rs
> +pub async fn reconcile_znode(
This method needs inline code documentation

2021-11-23 15:07 UTC, lfrancke commented on rust/operator-binary/src/znode_controller.rs
> +    let znode_path = format!("/znode-{}", uid);
Why the `znode` prefix?

2021-11-23 15:07 UTC, lfrancke commented on rust/operator-binary/src/znode_controller.rs
> +//! Ensures that ZooKeeper ZNodes (filesystem nodes) exist for each [`ZookeeperZnode`], and creates discovery [`ConfigMap`]s for them
Even after reading the code I don't really understand what this is for/doing.
Could you elaborate?

2021-11-24 09:11 UTC, teozkr commented on rust/crd/Cargo.toml
> +version = "0.1.0"
e231a16ef8494f5f5c06df4f6daba3940b95b0db

2021-11-24 09:12 UTC, teozkr commented on rust/operator-binary/Cargo.toml
> +eyre = "0.6.5"
Force of habit. `eyre` has some error formatting hooks that are useful when running standalone (see https://docs.rs/color-eyre/0.5.11/color_eyre/), but not so much when we use `tracing` for error reporting anyway.

2021-11-24 09:21 UTC, teozkr commented on rust/operator-binary/Cargo.toml
> +eyre = "0.6.5"
e0de2ef755e17c9d8fed5d2e1c634f7f7e7f7816

2021-11-24 09:34 UTC, teozkr commented on rust/operator-binary/src/main.rs
> +            let product_config = ProductConfigManager::from_str(include_str!(
f4f610829e38ae47d0ffcedd7358b69c4f94bf32

Added a `FrameworkOpts` that we can move into operator-rs (fulfilling the same role as `generate_productconfig_arg`).

2021-11-24 09:37 UTC, teozkr commented on rust/operator-binary/src/main.rs
> +fn erase_controller_result<K: Resource, E: std::error::Error + Send + Sync + 'static>(
Tried with feb7a2a8bf2da0e973fb3155fff0810e74ca18ef, but not sure it's a massive improvement.

2021-11-24 09:42 UTC, teozkr commented on rust/operator-binary/src/utils.rs
> +pub async fn apply_owned<K>(kube: &kube::Client, field_manager: &str, obj: &K) -> kube::Result<K>
d16e20c3f78a856bf81d87ca09db04399a3465f8

2021-11-24 09:45 UTC, teozkr commented on rust/operator-binary/src/utils.rs
> +pub fn controller_reference_to_obj<K: Resource<DynamicType = ()>>(obj: &K) -> OwnerReference {
It was meant as "controller reference that refers to object", but now that you mention it I can see how "convert controller reference into object" is also a reasonable interpretation of the name.

Maybe `controller_reference_for_obj` would be clearer, but that could also be read as "try to find the controller reference of object".

2021-11-24 09:50 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +    #[snafu(display("object {} has no namespace", obj_ref))]
Force of habit again, mostly. I would say that SNAFU's backchannel source propagation is a nice help in making sure that propagating the source is the ergonomic choice that actually gets taken.

2021-11-24 09:51 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +pub async fn reconcile_zk(
Yeah, need to get around to breaking this into more concrete functions.

2021-11-24 09:53 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +    let container_decide_myid = ContainerBuilder::new("decide-myid")
That script only supports writing a predetermined ID, which is frankly the trivial part of that script.

2021-11-24 12:09 UTC, teozkr commented on rust/operator-binary/src/znode_controller.rs
> +    let znode_path = format!("/znode-{}", uid);
To demarcate provisioned operator-managed ZNodes from ZNodes from other sources (such as `/zookeeper`). The name format is taken from K8s naming all dynamically provisioned PVs `pvc-{pvc-uid}`. But I agree that this prefix in particular isn't very helpful and should probably be improved.

2021-11-24 12:29 UTC, teozkr commented on rust/operator-binary/src/znode_controller.rs
> +//! Ensures that ZooKeeper ZNodes (filesystem nodes) exist for each [`ZookeeperZnode`], and creates discovery [`ConfigMap`]s for them
I assume this is as much about the `ZookeeperZnode` resource as it is about the controller.

Basically, this comes down to the difference between `hostPath` and using `PersistentVolumeClaim`s. Instead of giving everyone full access to the ZooKeeper cluster and hoping things work out, you request a unique namespace (by creating a `ZookeeperZnode`) and get back a connection string that is chrooted to that znode.

This becomes even more important when authn/z enters the picture, since we probably don't want to give everyone full write access to the root znode.

But yeah, the documentation here should certainly be improved...

2021-11-24 13:59 UTC, maltesander commented on rust/operator-binary/src/zk_controller.rs
> +    let container_decide_myid = ContainerBuilder::new("decide-myid")
Yeah we just took the node_id from the sticky scheduler and wrote that.

2021-11-24 14:04 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +                    "exec 3<>/dev/tcp/localhost/2181 && echo srvr >&3 && grep '^Mode: ' <&3"
I can agree with adding a comment for this (it.. could be clearer), but I'm not sure this is something that we need to surface to end users. "Servers that are down do not participate in load balancing" kind of feels like it goes without saying.

2021-11-24 14:08 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +        .add_container_port("zk", 2181)
Maybe, the question here is how valuable it is to support configurable ports when running on the overlay network. I could see an argument for configuring `nodePort`. But I'm not really sure how that fits into product-config when it's not really a config property of the product itself.

2021-11-24 16:03 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +pub async fn reconcile_zk(
aa57beb0a9e383ede87da5588e39e7c596432e54 tries to improve on the situation a bit

2021-11-24 16:03 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +                    "exec 3<>/dev/tcp/localhost/2181 && echo srvr >&3 && grep '^Mode: ' <&3"
bb74e836f506b58c2301d4bfd6be1e75158901ba

2021-11-25 09:26 UTC, teozkr commented on rust/operator-binary/src/utils.rs
> +pub fn controller_reference_to_obj<K: Resource<DynamicType = ()>>(obj: &K) -> OwnerReference {
Deleted in 7acfa2012ea0a7e3f9ba3719901de7575b016861

2021-11-25 09:45 UTC, teozkr commented on rust/operator-binary/src/znode_controller.rs
> +//! Ensures that ZooKeeper ZNodes (filesystem nodes) exist for each [`ZookeeperZnode`], and creates discovery [`ConfigMap`]s for them
Tried to rewrite it to be a bit clearer in 1a47573c4ccf145fc610ba4973173a39d3e63fa4, but not sure it was successful

2021-11-25 09:57 UTC, teozkr commented on rust/operator-binary/src/znode_controller.rs
> +pub async fn reconcile_znode(
1085b13082c180bc5c4b99935cc80346ad4b2628

2021-11-25 10:00 UTC, teozkr commented
@lfrancke Think I addressed all of your feedback points now. I'll do a pass through the antora docs once #276 is merged.

2021-11-26 11:05 UTC, lfrancke commented on rust/operator-binary/src/zk_controller.rs
> +                    "exec 3<>/dev/tcp/localhost/2181 && echo srvr >&3 && grep '^Mode: ' <&3"
Yes and no. The ports can be changed (i.e. people can change port 2181) and the readiness probe would fail if they do.

So this should really take the configured ports instead.

Also: I've never heard of /dev/tcp :O
Also2: If it's easier with telnet or netcat or there are other benefits that's even more of a reason to build our own stackable-utils image.

2021-11-26 11:05 UTC, lfrancke commented on rust/operator-binary/src/znode_controller.rs
> +//! See [`ZookeeperZnode`] for more details.
You are allowed to call me stupid but even after reading the `ZookeeperZnode` docs I still have no real idea what's going on or where and how this would be used.

It is for service discovery somehow...to get connection strings for the ZooKeeper cluster somehow...

2021-11-26 11:05 UTC, lfrancke commented on rust/operator-binary/src/znode_controller.rs
> +//! See [`ZookeeperZnode`] for more details.
Also: (And I thought I commented about this before but can't find it) This is going to be fragile because of hardcoded assumptions (like port and no-security).

I'm fine with that for now as long as we track this somewhere.

2021-11-29 09:35 UTC, teozkr commented on rust/operator-binary/src/utils.rs
> +pub async fn apply_owned<K>(kube: &kube::Client, field_manager: &str, obj: &K) -> kube::Result<K>
Yep.

2021-11-29 09:39 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +                    "exec 3<>/dev/tcp/localhost/2181 && echo srvr >&3 && grep '^Mode: ' <&3"
> So this should really take the configured ports instead.

That boils down to the discussion at https://github.com/stackabletech/zookeeper-operator/pull/263#discussion_r755201600. If we do support changing ports then yes, we'll need to change the probe to accommodate that.

>  Also2: If it's easier with telnet or netcat or there are other benefits that's even more of a reason to build our own stackable-utils image.

With netcat it'd be `echo srvr | nc localhost 2181 | grep '^Mode: '`. Not much easier for these trivial cases, but I'd say it makes the pipeline a bit easier to read.

> Also: I've never heard of /dev/tcp :O

Yeah, it's one of those weird bashisms... :P

2021-11-29 09:41 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +/// The rolegroup [`ConfigMap`].. configures the rolegroup based on the configuration given by the administrator
13d69131f561dda2f83a694cc9b2b3c4c38c71da

2021-11-29 09:42 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +                    "exec 3<>/dev/tcp/localhost/2181 && echo srvr >&3 && grep '^Mode: ' <&3"
That said, this (in particular) wouldn't really be helped by stackable-utils, since probes run in the same container as the container they're probing.

2021-11-29 10:37 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
>          .image("alpine")
Looks like we can actually get away with using the zookeeper image there instead.

That said, preferring our own `stackable-utils` image for when we actually need that over UBI makes sense to me.

2021-11-29 12:08 UTC, teozkr commented on rust/operator-binary/src/znode_controller.rs
> +//! See [`ZookeeperZnode`] for more details.
> You are allowed to call me stupid but even after reading the ZookeeperZnode docs I still have no real idea what's going on or where and how this would be used.
>
> It is for service discovery somehow...to get connection strings for the ZooKeeper cluster somehow...

Do you have time to jump on a call some time? Right now it feels like I'm flailing in the dark. (Obviously, this needs to feed back into the docs.)

> Also: (And I thought I commented about this before but can't find it) This is going to be fragile because of hardcoded assumptions (like port and no-security).

The assumptions have to go somewhere. The idea here is to tie them into the entity making those decisions (the operator) instead of having every downstream client make the assumptions on their own.

If we want to support overriding the port then we would "just" carry that over into here as well. TLS/authn is a slightly trickier bridge to cross since that means we'll have to start injecting certificates and configuration, but the same basic principle applies.

2021-11-30 23:23 UTC, lfrancke commented on rust/operator-binary/src/zk_controller.rs
> +    #[snafu(display("object {} has no namespace", obj_ref))]
I'm fine with snafu if we have a good reason for it which we seem to.

2021-12-02 09:32 UTC, lfrancke commented on rust/operator-binary/src/main.rs
> +}
I like this a lot. Can we move it to the Run subcommand only? The option doesn't make sense for the Crd subcommand

2021-12-02 09:37 UTC, lfrancke commented on rust/crd/src/lib.rs
> +    pub servers: RoleGroup<ZookeeperConfig>,
This should be a `Role` and not just a `RoleGroup`

2021-12-02 11:34 UTC, lfrancke commented
We had a call about the remaining open issues and came up with this plan/these decisions:

- We are going to use the overlay network
- We are going to create two ConfigMaps for each ZNode AND also two ConfigMaps for each ZooKeeper object itself: One for the internal network and one for the external one
- We are going to add support for Role & multiple role groups, if users specify more than one role group they manually need to specify an id offset for each group
- We are not going to tackle different storage types in this PR
- We are only going to include monitoring/JMX if there is enough time (low priority), same goes for user-facing docs

2021-12-02 13:28 UTC, maltesander commented on examples/simple-zookeeperznode.yaml
> +    name: simple-zkc
This does not fit the ZookeeperCluster example:
`simple-zkc` vs `simple-zk`

2021-12-02 13:45 UTC, teozkr commented on examples/simple-zookeeperznode.yaml
> +    name: simple-zkc
Fixed in https://github.com/stackabletech/zookeeper-operator/pull/263/commits/ffbfff7abe1683dc2cf86143b799d61bb1129bac#diff-ecda3e0c9a92681434e0606e72e12dd169b5a708d0904ac8894b86efd284c620

2021-12-03 16:12 UTC, lfrancke reviewed
All in all I like it. Thank you for the improvements. I only left a single or two minor comments I believe.

One thing that would have helped me would have been inline comments.
The code is pretty "small" and succinct but it is alo "clever" in some parts which makes it harder for me to read.
I understand that this is an unfair comment that you can't realy act upon.

I'd love it if someone else could also take a quick look as part of the hackathon next week maybe.

I believe you mentioned the only missing thing are docs. Those can but don't have to block a merge.

2021-12-03 16:12 UTC, lfrancke commented on rust/crd/src/lib.rs
> +    pub zookeeper_id: u16,
Isn't this the `myid`? If not it'd be good to document what this is.

2021-12-03 20:00 UTC, teozkr commented on rust/crd/src/lib.rs
> +    pub fn pods(&self) -> Result<impl Iterator<Item = ZookeeperPodRef> + '_, NoNamespaceError> {
Yes. We generate references to the pods that we expect to have once the cluster is actually up and running. That way we can avoid a bunch of churn in both discovery CMs and server config while the service is scaling up or down.

That should probably go into a comment, yes.

2021-12-03 20:00 UTC, teozkr commented on rust/crd/src/lib.rs
> +    pub zookeeper_id: u16,
Yes. Would `zookeeper_myid` be clearer?

2021-12-06 12:40 UTC, teozkr commented on rust/crd/src/lib.rs
> +    pub fn pods(&self) -> Result<impl Iterator<Item = ZookeeperPodRef> + '_, NoNamespaceError> {
e74c016d286e5112aab9cc6cac7607630eb936aa

2021-12-06 12:41 UTC, teozkr commented on rust/crd/src/lib.rs
> +    pub zookeeper_id: u16,
8c24f11318753a1e172925ce2cd62cb7af4bd730

2021-12-13 10:52 UTC, teozkr commented on rust/operator-binary/Cargo.toml
> +# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
5c60f6ecb79b1f083993b3f3bbdcd35e06d4c0e4

2021-12-13 10:55 UTC, teozkr commented on rust/operator-binary/src/znode_controller.rs
> +//! See [`ZookeeperZnode`] for more details.
Added some more context in 5c44afaadc31e6b1a76faa67d80ab9820840fd4e, obviously further improvements would be welcome here.

2021-12-14 10:41 UTC, maltesander reviewed
Just some comments about builders. I think we should provide builders for StatefulSets, Services etc in the framework as well?

2021-12-14 10:41 UTC, maltesander commented on rust/operator-binary/src/zk_controller.rs
> +    let zk_version = zk.spec.version.as_deref().context(ObjectHasNoVersion)?;
You have the `zk_version` method for that.

2021-12-14 10:41 UTC, maltesander commented on rust/operator-binary/src/zk_controller.rs
> +    })
Should we create builders in operator-rs for that as well to be consistent?

2021-12-14 10:41 UTC, maltesander commented on rust/operator-binary/src/zk_controller.rs
> +            },
Builders? I know its a lot of code but it helped us before to have another layer of code between the operators and kube-rs?

2021-12-14 10:41 UTC, maltesander commented on rust/operator-binary/src/zk_controller.rs
> +            ..StatefulSetSpec::default()
Builders again ;) ?

2021-12-14 10:48 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +    let zk_version = zk.spec.version.as_deref().context(ObjectHasNoVersion)?;
Good point, legacy stuff. 2a72bd9e58916a5d482e6c41501556188a9229f7

2021-12-14 10:52 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +    })
I think it would probably make sense at some point, yes. Maybe even helpers for role/rolegroup services in particular. That said, I think that's more of a refactoring for later than something critical to get right in the initial merge?

2021-12-14 10:53 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +            },
As with services, it probably makes sense at some point, there's just the question of when.

2021-12-14 10:55 UTC, teozkr commented on rust/operator-binary/src/zk_controller.rs
> +            ..StatefulSetSpec::default()
Same answer again ;)

2021-12-14 11:41 UTC, maltesander commented on rust/operator-binary/src/zk_controller.rs
> +    })
Yeah fine with me, ill make a mental note!

2021-12-14 11:46 UTC, maltesander commented on rust/crd/src/lib.rs
> +        let jvm_flags = "-javaagent:/stackable/jmx/jmx_prometheus_javaagent-0.16.1.jar=9505:/stackable/jmx/server.yaml".to_string();
One last thing. I think we always want monitoring enabled, so im fine with doing it here like this. Do we need to configure the port? This would affect this part and the pod container ports?

2021-12-14 11:48 UTC, lfrancke approved these changes
One comment about the docs but I'd be fine merging this.
Thank you so much for all the work that went into this.

2021-12-14 11:48 UTC, lfrancke commented on docs/modules/ROOT/pages/usage.adoc
> +Afterwards, a ZookeeperZnode root can be created:
There's not really an explanation anywhere what this is.

2021-12-14 12:50 UTC, teozkr commented on rust/crd/src/lib.rs
> +        let jvm_flags = "-javaagent:/stackable/jmx/jmx_prometheus_javaagent-0.16.1.jar=9505:/stackable/jmx/server.yaml".to_string();
> Do we need to configure the port?

I don't think so, we just need to inform Prometheus about which port to scrape.

2021-12-14 12:51 UTC, teozkr commented on docs/modules/ROOT/pages/usage.adoc
> +Afterwards, a ZookeeperZnode root can be created:
Yeah, I think this is a more general issue for the docs at the moment. For 0.1 I just wanted to make a note that it should be used.

2021-12-14 13:16 UTC, maltesander commented on rust/crd/src/lib.rs
> +        let jvm_flags = "-javaagent:/stackable/jmx/jmx_prometheus_javaagent-0.16.1.jar=9505:/stackable/jmx/server.yaml".to_string();
Ok, currently for our monitoring operator we do this via container port `metrics` and a boolean annotation `SHOULD_BE_SCRAPED`. But this probably will change to just having a metrics port in the annotation.

The question is as long as we have operators using the host network, we should be able to configure all the ports to avoid conflicts? Not applying here, more a general thought of consistency.

2021-12-14 15:05 UTC, teozkr commented on rust/crd/src/lib.rs
> +        let jvm_flags = "-javaagent:/stackable/jmx/jmx_prometheus_javaagent-0.16.1.jar=9505:/stackable/jmx/server.yaml".to_string();
> But this probably will change to just having a metrics port in the annotation.

Yeah.

> The question is as long as we have operators using the host network, we should be able to configure all the ports to avoid conflicts? Not applying here, more a general thought of consistency.

Yeah, all or nothing is probably the sensible rule there.

2021-12-14 15:07 UTC, merged