docs: getting started guide
stackabletech/zookeeper-operator pull request #537
Opened 2022-08-11 13:04 UTC by fhennig

# Description

fixes #536

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-08-18 14:32 UTC, maltesander requested changes
So the script did not work with helm for me (i saw the flaky comment). Any ideas why?:
```
malte@mdesktop ~/d/w/z/d/m/g/e/code (getting-started) [1]> ./getting_started.sh helm
Adding 'stackable-dev' Helm Chart repository
"stackable-dev" already exists with the same configuration, skipping
Installing Operators with Helm
NAME: commons-operator
LAST DEPLOYED: Thu Aug 18 16:23:49 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NAME: secret-operator
LAST DEPLOYED: Thu Aug 18 16:24:04 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NAME: zookeeper-operator
LAST DEPLOYED: Thu Aug 18 16:24:07 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Creating ZooKeeper cluster
zookeepercluster.zookeeper.stackable.tech/simple-zk created
Awaiting ZooKeeper rollout finish
Waiting for 2 pods to be ready...
Waiting for 2 pods to be ready...
Waiting for 2 pods to be ready...
Waiting for 1 pods to be ready...
partitioned roll out complete: 2 new pods have been updated...
zkCli.sh ls command did not work. command output:

```

It worked fine via stackablectl:
```
malte@mdesktop ~/d/w/z/d/m/g/e/code (getting-started) [1]> ./getting_started.sh stackablectl
installing Operators with stackablectl
[INFO ] Installing commons operator in version 0.3.0-nightly
[INFO ] Installing secret operator in version 0.6.0-nightly
[INFO ] Installing zookeeper operator in version 0.11.0-nightly
Creating ZooKeeper cluster
zookeepercluster.zookeeper.stackable.tech/simple-zk created
Awaiting ZooKeeper rollout finish
Waiting for 2 pods to be ready...
Waiting for 2 pods to be ready...
Waiting for 1 pods to be ready...
Waiting for 1 pods to be ready...
partitioned roll out complete: 2 new pods have been updated...
zkCli.sh ls command worked
Applying ZNode
zookeeperznode.zookeeper.stackable.tech/simple-znode created
zkCli.sh ls command worked
ConfigMap retrieved.
ConfigMap contains a reference of the ZNode
Script ran successfully!

```

2022-08-18 14:32 UTC, maltesander commented on docs/modules/getting_started/pages/index.adoc
> +This guide will get you started with ZooKeeper using the Stackable Operator. It will guide you through the installation of the Operator and its dependencies, setting up your first ZooKeeper cluster a
We could link to the ZNode concept?
```suggestion
This guide will get you started with Apache ZooKeeper using the Stackable Operator. It will guide you through the installation of the Operator and its dependencies, setting up your first ZooKeeper cluster and connecting to it as well as setting up your first xref:ROOT:znodes.adoc[ZNode].
```

2022-08-18 14:32 UTC, maltesander commented on docs/modules/getting_started/pages/installation.adoc
> +[INFO ] Installing zookeeper operator
That output is not 100% correct as the version is missing. Check the templated stuff in e.g. Hive as we discussed.

2022-08-18 14:32 UTC, maltesander commented on docs/modules/getting_started/pages/first_steps.adoc
> +Have a look at the xref:ROOT:usage.adoc[] page to learn more about configuration options for you ZooKeeper cluster like setting up encryption or authentication. You can also have a look at the xref:R
```suggestion
Have a look at the xref:ROOT:usage.adoc[] page to learn more about configuration options for your ZooKeeper cluster like setting up encryption or authentication. You can also have a look at the xref:ROOT:znodes.adoc[] page to learn more about ZNodes.
```

2022-08-18 14:32 UTC, maltesander commented on docs/modules/getting_started/pages/first_steps.adoc
> +The `ZOOKEEPER_CHROOT` and `ZOOKEEPER_HOSTS` entries contain the node name and hosts list respectively. You can use these three entries mounted into a pod to connect to ZooKeeper at this specific ZNo
```suggestion
The `ZOOKEEPER_CHROOT` and `ZOOKEEPER_HOSTS` entries contain the node name and hosts list respectively. You can use these three entries mounted into a pod to connect to ZooKeeper at this specific ZNode and read/write in that ZNode directory.
```

2022-08-18 14:32 UTC, maltesander commented on docs/modules/getting_started/pages/first_steps.adoc
> +ZNodes are created with manifest files too, of the kind ZookeeperZnode. Create a file called `znode.yaml` with the following contents:
```suggestion
ZNodes are created with manifest files of the kind `ZookeeperZnode`. Create a file called `znode.yaml` with the following contents:
```

2022-08-18 14:32 UTC, maltesander commented on docs/modules/getting_started/pages/first_steps.adoc
> +The Operator deploys readiness probes to make sure the replicas are in quorum. Only then will the StefulSet actually be marked as `Ready`. You will see
```suggestion
The Operator deploys readiness probes to make sure the replicas are ready and established a quorum. Only then will the StefulSet actually be marked as `Ready`. You will see
```

2022-08-18 14:32 UTC, maltesander commented on docs/modules/getting_started/examples/code/zookeeper.yaml
> +        replicas: 2
You cannot establish a quorum with just 2 replicas (i think the cluster will still come up, but quorum is mentioned somewhere for readiness so i would use a correct value).
```suggestion
        replicas: 3
```

2022-08-18 14:32 UTC, maltesander commented on docs/modules/getting_started/examples/code/getting_started.sh.j2
> +# No running processes are left behind (i.e. the port-forwarding is closed at the end)
Maybe specify on your local machine, but the cluster is not cleaned up so there is some stuff left behind ;)

2022-08-22 13:54 UTC, maltesander requested changes
Just minor stuff.

2022-08-22 13:54 UTC, maltesander commented on docs/modules/getting_started/examples/code/getting_started.sh.j2
> +# NOTE: This command sporadically fails in kind. It works well in other k8s implementations.
I would change this (not longer valid). Can we explain / link the issue why we do it this complicated ;)? Dont forget to run the templating script.

2022-08-22 13:54 UTC, maltesander commented on docs/modules/getting_started/pages/first_steps.adoc
> +The ZooKeeper is now ready.
```suggestion
The ZooKeeper cluster is now ready.
```

2022-08-22 13:54 UTC, maltesander commented on docs/modules/getting_started/pages/first_steps.adoc
> +ZooKeeper manages its data in a hierarchical node system. You can look at the nodes using the zkCli tool. It is included inside of Stackable ZooKeeper container, and you can invoke it using `kubectl
```suggestion
ZooKeeper manages its data in a hierarchical node system. You can look at the nodes using the zkCli tool. It is included inside the Stackable ZooKeeper container, and you can invoke it using `kubectl run`:
```

2022-08-22 13:54 UTC, maltesander commented on docs/modules/getting_started/pages/first_steps.adoc
> +Among log output you will see the current list of nodes in `/`:
```suggestion
Among the log output you will see the current list of nodes in the root directory `/`:
```

2022-08-22 13:54 UTC, maltesander commented on docs/modules/getting_started/pages/first_steps.adoc
> +You will get output similar to this:
```suggestion
You will see an output similar to this:
```

2022-08-22 13:58 UTC, fhennig commented on docs/modules/getting_started/examples/code/getting_started.sh.j2
> +# NOTE: This command sporadically fails in kind. It works well in other k8s implementations.
updated it :D

2022-08-22 14:01 UTC, maltesander approved these changes
LGTM.

2022-08-22 14:01 UTC, fhennig commented
bors merge

2022-08-22 14:12 UTC, closed without merging