Split off usage guide into individual files and document MyID for multiple role groups
stackabletech/zookeeper-operator pull request #606
Opened 2022-12-13 14:21 UTC by fhennig

# Description

fixes #557 

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-12-13 16:06 UTC, maltesander requested changes

2022-12-14 08:17 UTC, fhennig commented on docs/modules/usage_guide/pages/using_multiple_role_groups.adoc
> +The offset is configured with the `myidOffset` config option on a role group:
Thanks for the suggestion!

2022-12-14 08:27 UTC, fhennig commented on docs/modules/usage_guide/pages/configuration_environment_overrides.adoc
> +----
The storage bit above it as well I think. I'm moving it. But it was in the override section before, that's why it's in there. I didn't want to change the hierarchy of sections, just split them

2022-12-14 11:46 UTC, maltesander approved these changes
LGTM!

2022-12-14 11:50 UTC, fhennig commented
bors merge

2022-12-14 11:56 UTC, closed without merging