Created build process for RPM package
stackabletech/zookeeper-operator pull request #66
Opened 2021-03-12 14:37 UTC by soenkeliebau

This creates a build and publish step for an RPM package.

I decided against using the cargo-rpm module, as this has issues with long filenames in its current version. 
On top of that I felt like it added limited value for a lot less insight into the build process. Documentation for that project is close to non existent.

2021-03-15 15:14 UTC, lfrancke requested changes

2021-03-15 15:14 UTC, lfrancke commented on .github/workflows/nightly.yml
> +  centos7:
Can this be refactored into a build matrix?
https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

2021-03-15 15:14 UTC, lfrancke commented on .github/workflows/nightly.yml
> +      - name: Build rpm package
```suggestion
      - name: Build RPM package
```

2021-03-15 15:14 UTC, lfrancke commented on .github/workflows/nightly.yml
> +      - name: Publish rpm package
```suggestion
      - name: Publish RPM package
```

2021-03-15 15:14 UTC, lfrancke commented on .github/workflows/nightly.yml
> +      - name: Build rpm package
```suggestion
      - name: Build RPM package
```

2021-03-15 15:14 UTC, lfrancke commented on .github/workflows/nightly.yml
> +      - name: Publish rpm package
```suggestion
      - name: Publish RPM package
```

2021-03-15 15:14 UTC, lfrancke commented on server/packaging/buildrpm.sh
> +echo Creating directory scaffolding for rpm
```suggestion
echo Creating directory scaffolding for RPM
```

2021-03-15 15:14 UTC, lfrancke commented on server/packaging/buildrpm.sh
> +export PACKAGE_DESCRIPTION=$(cat server/packaging/description)
I understand why but that's not great.
`cargo metadata` doesn't seem to be able to filter by field...

2021-03-15 15:14 UTC, lfrancke commented on server/Cargo.toml
> +[package.metadata.rpm]
Are these leftovers from the cargo-rpm experiments?

2021-03-15 16:07 UTC, soenkeliebau commented on .github/workflows/nightly.yml
> +      - rpm
I didn't expect to get this through without changes requested and left it in so that I could test after addressing comments.

2021-03-15 16:08 UTC, soenkeliebau commented on server/Cargo.toml
> +[package.metadata.rpm]
Yes

2021-03-15 16:15 UTC, soenkeliebau commented on server/packaging/buildrpm.sh
> +export PACKAGE_DESCRIPTION=$(cat server/packaging/description)
I'm open to alternatives, but as far as I could tell `cargo metadata` doesn't even give us that field.
We could do something like `cat server/Cargo.toml|grep "^description =" | awk -F " = " '{print $2}'` but that didn't feel much better tbh.

2021-03-15 16:19 UTC, soenkeliebau commented on .github/workflows/nightly.yml
> +  centos7:
From my understanding of matrix builds it could, but this does the job and I didn't want to spend time reading up on them. 
Happy to do it of course, but it wouldn't really add value at the moment I think.

2021-03-15 22:17 UTC, lfrancke submitted a review, later dismissed
Looks good to me, in principle. Just need to remove the RPM from the branches list

2021-03-16 09:19 UTC, soenkeliebau commented on server/packaging/buildrpm.sh
> +export PACKAGE_DESCRIPTION=$(cat server/packaging/description)
I have changed this to read the description from `cargo metadata` by parsing the json that it returns with jq. I am not entirely sure that this will never break to be honest, but it works for now and doesn't require tracking the description in a second place.

2021-03-16 09:19 UTC, soenkeliebau commented on .github/workflows/nightly.yml
> +      - rpm
Removed in preparation for merging this.

2021-03-16 09:59 UTC, lfrancke approved these changes

2021-03-16 10:07 UTC, merged