Allow upgrades for ZK Operator
stackabletech/zookeeper-operator pull request #67
Opened 2021-03-17 13:40 UTC by lfrancke

This will only allow rolling upgrades at the moment.

This might fail due to 
https://issues.apache.org/jira/browse/ZOOKEEPER-3781
https://issues.apache.org/jira/browse/ZOOKEEPER-3513

/closes #37

2021-03-17 14:11 UTC, lfrancke commented
I should probably check this again against the Spark operator and there's an issue that will make the upgrade fail.
I'm not sure if we want to invest in fixing that considering 3.4 is relatively old and in theory newer versions should be backwards compatible with 3.4

2021-03-17 14:59 UTC, maltesander requested changes
Just a some notes to the ZookeeperVersion and a general thing about cleaning up configmaps.

2021-03-17 14:59 UTC, maltesander commented on crd/src/lib.rs
> +            )
You can just use version.to_string() here since you derive from strum_macros::Display.
            format!("stackable/zookeeper:{}", version.to_string())

2021-03-17 14:59 UTC, maltesander commented on operator/src/lib.rs
> +                        &format!("Initial installation to version [{:?}]", spec_version),
Wont change alot, but we could use spec_version.to_string() here (and below) as well instead of debug.

2021-03-17 14:59 UTC, maltesander commented on operator/src/lib.rs
>                  self.context.client.delete(&pod).await?;
You create one configmap for every pod right? Then for every pod delete (here and in read_existing_pod_information()), we should have a configmap delete? Its not done in the spark operator either yet, but its a little different since multiple pods may share a configmap depending on the selector.

2021-03-25 10:13 UTC, lfrancke commented on operator/src/lib.rs
>                  self.context.client.delete(&pod).await?;
At the moment I create two configmaps per Pod, yes. This'll change once we adapted to ADR009 and they are created with blockOwnerDeletion so the Garbage Collector will clean them up once the parent is removed.

Also see https://github.com/stackabletech/issues/issues/10

2021-03-25 11:18 UTC, maltesander approved these changes

2021-03-25 11:18 UTC, merged