Support podOverrides
stackabletech/zookeeper-operator pull request #698
Opened 2023-06-28 12:11 UTC by sbernauer

# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2023-06-29 13:10 UTC, maltesander requested changes
Minor things.
Do we need an integration test? Currently if anything in the DeepMerge changes we wont fail anywhere?

2023-06-29 13:10 UTC, maltesander commented on rust/operator-binary/src/zk_controller.rs
> +    #[snafu(display("internal operator failure: {source}"))]
No need to mention the source in the message.
```suggestion
    #[snafu(display("internal operator failure"))]
```

2023-06-29 13:10 UTC, maltesander commented on rust/crd/src/lib.rs
> +
Do we really need this for one role?

2023-06-29 14:06 UTC, sbernauer commented on rust/crd/src/lib.rs
> +
I just copy-pasted it from trino-op. We could hardcode the list, but I personally prefer it this way for
1. Consistency
2. If (given unlikely) we add a role we are not introducing a bug when we forget about this

2023-06-30 09:38 UTC, sbernauer commented
I think the effort of maintaining this tests does not justify testing something coming from k8s-openapi.
The only thing we could test is our two `.merge()` statements, where it personally think it's not worth it.

2023-06-30 12:15 UTC, maltesander commented on rust/crd/src/lib.rs
> +
Ok works for me.

2023-06-30 12:15 UTC, maltesander approved these changes
LGTM!

2023-07-03 10:35 UTC, sbernauer commented
bors r+

2023-07-03 10:39 UTC, closed without merging