Allow changing configuration options
stackabletech/zookeeper-operator pull request #71
Opened 2021-03-22 14:03 UTC by lfrancke

This PR contains multiple changes:
- Adapt to latest operator-rs and kube 0.57
- Add product config validation and properties file
- Add graceful wait if CRD is missing
- Changed version "v1" to "v1alpha1"

2021-07-13 12:57 UTC, soenkeliebau requested changes
left a few comments

2021-07-13 12:57 UTC, soenkeliebau commented on config.yaml
> +          required: true
I think this and syncLimit are only mandatory, when more than one server is specified I think. Probably not that important to implement right now, but maybe worthwhile noting..

2021-07-13 12:57 UTC, soenkeliebau commented on crd/src/lib.rs
> +        let temp = product_config::ser::to_hash_map(self).unwrap();
Can you please catch this unwrap and log a proper error?

2021-07-13 12:57 UTC, soenkeliebau commented on operator/src/lib.rs
> +                self.context.client.create(&config_map).await?;
Could this not be handled by a simple pattern match sort of like here: https://github.com/stackabletech/operator-rs/blob/9f5adb01c7a3fb275134679c499bed83ebbd36b6/src/client.rs#L95

2021-07-13 18:28 UTC, maltesander commented on config.yaml
> +      comment: "ZK only checks whether the value is 0, all other values (including negative ones) are considered valid, we disallow negative values here, see QuorumPeerConfig.java"
That is the Zookeeper property description :)
What do you mean with overriden? Our config overrides?

2021-07-13 18:33 UTC, maltesander commented on config.yaml
> +          required: true
Hmm not sure how to model that. I think normal usage will be at least 3 zookeepers? I add a comment in the config.

2021-07-13 18:40 UTC, maltesander commented on operator/src/lib.rs
> +                self.context.client.create(&config_map).await?;
Not sure what you mean? It is a pattern match already?

2021-07-15 07:59 UTC, soenkeliebau commented on config.yaml
> +      comment: "ZK only checks whether the value is 0, all other values (including negative ones) are considered valid, we disallow negative values here, see QuorumPeerConfig.java"
In that case I don't understand the description I think :)

It sounded to me like ZooKeeper would allow negative values but Stackable filters these out - and my question was if the customers can override that filtering if they have a good reason.

2021-07-15 08:00 UTC, soenkeliebau commented on config.yaml
> +          required: true
ZooKeeper distinguishes `cluster settings` which are only applicable when running in cluster mode with more than one servers. 
I think we can safely ignore that for now, but might want to revisit at some point in time when we refine the product config code more.

2021-07-15 08:08 UTC, soenkeliebau commented on operator/src/lib.rs
> +                self.context.client.create(&config_map).await?;
I may have misunderstood the code here, but to me this looks like it tries to create the configmap when it gets an error from the .get(..) call. Which is ok if the error is "not found", but for most other errors this would probably mean that there is an issue talking to Kubernetes and the creation will also fail.
My thought was to add a branch to the pattern match and treat "not found" differently from other errors.

Something like this: 

```rust
            Err(Error::KubeError {
                    source: kube::error::Error::Api(ErrorResponse { reason, .. }),
                }) if reason == "NotFound" => {
                debug!("Error getting ConfigMap [{}]: [{:?}]", cm_name, e);
                self.context.client.create(&config_map).await?;
            }
            Err(e) => {
                // abort
            }
```

2021-07-15 16:54 UTC, maltesander commented on config.yaml
> +      comment: "ZK only checks whether the value is 0, all other values (including negative ones) are considered valid, we disallow negative values here, see QuorumPeerConfig.java"
Yeah they can with config overrides (they are treated as strings, so negative values are possible as it should be parsed to i64 from product config.

2021-07-19 14:01 UTC, soenkeliebau approved these changes
LGTM (haven't tested the error handling myself, but discussed with @maltesander and he looked at it)

2021-07-19 14:06 UTC, merged