fix inconsistency in CRD for logging configuration
stackabletech/zookeeper-operator pull request #739
Opened 2023-11-02 13:56 UTC by fhennig

# Description
fixes #736 

TODO:
- update docs maybe?
- tests?

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

2023-11-02 14:30 UTC, maltesander commented
This has to be adapted in the integration tests of products using zookeeper (and maybe demos).

2023-11-03 09:01 UTC, fhennig commented
test run: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/zookeeper-operator-it-custom/66/

2023-11-03 11:08 UTC, maltesander requested changes
There are missing some changes in other integration tests. Just grep like:
```
    logging:
      vectorAggregatorConfigMapName:
```

2023-11-03 11:08 UTC, maltesander commented on CHANGELOG.md
> +- removed the `logging` layer in the `clusterConfig` CRD to make logging config consistent with other operators ([#739]).
```suggestion
- [BREAKING]: removed the `logging` layer in the `clusterConfig` CRD to make logging config consistent with other operators ([#739]).
```

2023-11-03 12:16 UTC, fhennig commented
new test run: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/zookeeper-operator-it-custom/68/

2023-11-03 13:55 UTC, maltesander approved these changes
LGTM!

2023-11-03 14:03 UTC, merged