feat: Support graceful shutdown
stackabletech/zookeeper-operator pull request #740
Opened 2023-11-03 10:36 UTC by sbernauer

# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

2023-11-03 12:01 UTC, sbernauer commented
Started https://ci.stackable.tech/job/zookeeper-operator-it-custom/67

2023-11-03 12:37 UTC, maltesander requested changes
Minor things, LGTM otherwise!

2023-11-03 12:37 UTC, maltesander commented on docs/modules/zookeeper/pages/usage_guide/operations/graceful-shutdown.adoc
> +As a default, server have `2 minutes` to shut down gracefully.
```suggestion
As a default, ZooKeeper server processes have `2 minutes` to shut down gracefully.
```

2023-11-03 12:37 UTC, maltesander commented on docs/modules/zookeeper/pages/usage_guide/operations/graceful-shutdown.adoc
> +The Zookeeper server process will receive a `SIGTERM` signal when Kubernetes wants to terminate the Pod.
```suggestion
The ZooKeeper server process will receive a `SIGTERM` signal when Kubernetes wants to terminate the Pod.
```

2023-11-03 12:37 UTC, maltesander commented on rust/operator-binary/src/zk_controller.rs
> +",
Can we indoc this? Looks abit weird :D

2023-11-03 12:59 UTC, sbernauer commented on docs/modules/zookeeper/pages/usage_guide/operations/graceful-shutdown.adoc
> +As a default, server have `2 minutes` to shut down gracefully.
I would like to avoid the term process, as the termiantionGracePeriodSeconds is set on the Pod and influences all containers with all processes inside (so also the bash script, vector etc.)
WDYT of
> As a default, ZooKeeper servers have `2 minutes` to shut down gracefully.

2023-11-03 12:59 UTC, sbernauer commented on rust/operator-binary/src/zk_controller.rs
> +",
514452d778c5851d2503293abd856ed1b95317ff

2023-11-06 08:48 UTC, maltesander commented on docs/modules/zookeeper/pages/usage_guide/operations/graceful-shutdown.adoc
> +As a default, server have `2 minutes` to shut down gracefully.
Yeah fine with me, adapted the suggestion to your proposal.

2023-11-06 09:02 UTC, maltesander approved these changes
LGTM!

2023-11-06 09:18 UTC, merged