Allow overriding ZNode path
stackabletech/zookeeper-operator pull request #799
Opened 2024-04-04 23:30 UTC by nightkr

# Description

Fixes https://github.com/stackabletech/zookeeper-operator/issues/681

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-04-05 00:04 UTC, nightkr commented
Some integration tests are currently failing due to a missing `spec.image`, not sure if it's related to https://stackable-workspace.slack.com/archives/C02M1RE8S0Z/p1712274080585689.

2024-04-26 15:27 UTC, nightkr commented
Turns out the test failures were due to stale beku work files. Clearing `tests/_work` made them pass.

2024-05-27 06:42 UTC, sbernauer requested changes
LGTM otherwise

2024-05-27 06:42 UTC, sbernauer commented on docs/modules/zookeeper/pages/usage_guide/isolating_clients_with_znodes.adoc
>  == What's next
I think we should move the newly added stuff above this, so that the "What's next" stays at the very bottom

2024-05-27 06:42 UTC, sbernauer commented on CHANGELOG.md
> +- ZNode path override ([#799]).
To me this sounds a bit clearer
```suggestion
- Allow overriding ZNode path by setting `status.znodePath` ([#799]).
```

2024-05-27 06:42 UTC, sbernauer commented on deploy/helm/zookeeper-operator/crds/crds.yaml
> +            status:
Out of scope: Ideally we would also have more status conditions (similar to ZookeeperCluster), e.g. if the ZNode has been created

2024-05-27 06:42 UTC, sbernauer commented on rust/operator-binary/src/znode_controller.rs
> +                znode.path = znode_path,
Do you by any chance have a guide on when to use nested fields? I have to admit I would have used `info!(znode_path, "...")`

2024-05-27 06:44 UTC, sbernauer commented on deploy/helm/zookeeper-operator/crds/crds.yaml
> +            status:
Created https://github.com/stackabletech/zookeeper-operator/issues/819

2024-06-03 12:44 UTC, nightkr commented on deploy/helm/zookeeper-operator/crds/crds.yaml
> +            status:
Agreed. Are we okay to resolve this convo since you made the issue?

2024-06-03 12:45 UTC, nightkr commented on CHANGELOG.md
> +- ZNode path override ([#799]).
I think this is closer but at the same time I don't think changelogs are meant to be documentation for how to use the feature.

2024-06-03 12:46 UTC, nightkr commented on docs/modules/zookeeper/pages/usage_guide/isolating_clients_with_znodes.adoc
>  == What's next
Sure.

2024-06-03 12:49 UTC, nightkr commented on docs/modules/zookeeper/pages/usage_guide/isolating_clients_with_znodes.adoc
>  == What's next
Actually, on second thought.. 

The znode path override is more of an appendix that should really belong in a reference section (or maybe a second guide). It's not part of the regular ZNode workflow that the guide covers primarily.

2024-06-03 14:20 UTC, sbernauer commented on deploy/helm/zookeeper-operator/crds/crds.yaml
> +            status:
Yeah, sure!

2024-06-03 14:23 UTC, sbernauer submitted a review, later dismissed

2024-06-03 22:21 UTC, nightkr commented on docs/modules/zookeeper/pages/usage_guide/isolating_clients_with_znodes.adoc
>  == What's next
I think it's worth doing a reference for znodes, but are we okay breaking that out of this PR?

2024-06-19 07:36 UTC, nightkr commented on docs/modules/zookeeper/pages/usage_guide/isolating_clients_with_znodes.adoc
>  == What's next
#824

2024-06-20 06:35 UTC, sbernauer commented on docs/modules/zookeeper/pages/usage_guide/isolating_clients_with_znodes.adoc
>  == What's next
I would still prefer to have the "Whats next" section at the end of the document, but not super important ;)

2024-06-20 06:35 UTC, sbernauer approved these changes

2024-06-20 06:37 UTC, merged