feat: Support non-default cluster domain
stackabletech/zookeeper-operator pull request #870
Opened 2024-10-21 08:58 UTC by maltesander

# Description

- bump to op-rs 0.79
- make cluster domain configurable

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-10-21 10:33 UTC, sbernauer commented
Running tests
kind https://testing.stackable.tech/job/zookeeper-operator-it-custom/2
AKS https://testing.stackable.tech/job/zookeeper-operator-it-custom/3
OpenShift https://testing.stackable.tech/job/zookeeper-operator-it-custom/4
GKE https://testing.stackable.tech/job/zookeeper-operator-it-custom/5
EKS https://testing.stackable.tech/job/zookeeper-operator-it-custom/6
IONOS https://testing.stackable.tech/job/zookeeper-operator-it-custom/7

2024-10-21 11:05 UTC, sbernauer requested changes

2024-10-21 11:05 UTC, sbernauer commented on rust/crd/src/lib.rs
> +            .expect("Could not resolve the Kubernetes cluster domain!");
I would prefer the longer message
```suggestion
            .expect("KUBERNETES_CLUSTER_DOMAIN must first be set by calling initialize_operator");
```

2024-10-21 11:05 UTC, sbernauer commented on rust/operator-binary/src/zk_controller.rs
> +        .unwrap()
Can we please use error handling everywhere?

2024-10-21 11:05 UTC, sbernauer commented on rust/operator-binary/src/zk_controller.rs
> +        .unwrap()
Can we please use error handling everywhere?

2024-10-21 11:05 UTC, sbernauer commented on rust/operator-binary/src/zk_controller.rs
> +            .unwrap(),
Can we please use error handling everywhere?

2024-10-22 08:20 UTC, maltesander commented on rust/operator-binary/src/zk_controller.rs
> +        .unwrap()
Thanks, done https://github.com/stackabletech/zookeeper-operator/pull/870/commits/59e2ea90cc3841c42a4e360079b2e0dfc91306c7

2024-10-22 08:20 UTC, maltesander commented on rust/operator-binary/src/zk_controller.rs
> +        .unwrap()
Thanks, done https://github.com/stackabletech/zookeeper-operator/pull/870/commits/59e2ea90cc3841c42a4e360079b2e0dfc91306c7

2024-10-22 08:20 UTC, maltesander commented on rust/operator-binary/src/zk_controller.rs
> +            .unwrap(),
Thanks, done https://github.com/stackabletech/zookeeper-operator/pull/870/commits/59e2ea90cc3841c42a4e360079b2e0dfc91306c7

2024-10-23 13:32 UTC, sbernauer approved these changes

2024-10-23 13:32 UTC, sbernauer commented on rust/operator-binary/src/zk_controller.rs
> +    .context(CreateClusterResourcesSnafu)?;
Thx!

2024-10-23 14:02 UTC, merged