Added first version of code to retrieve zookeeper connection string
stackabletech/zookeeper-operator pull request #88
Opened 2021-04-30 00:06 UTC by soenkeliebau

Zookeeper acts as backing store for many other services. Operators for these services will have to retrieve connection information from a Zookeeper object.

This PR adds a first version of function to retrieve the connection string from the api-server.
Functionality was added to the CRD crate, as this is the one that is most commonly used by other operators already.

2021-04-30 10:52 UTC, soenkeliebau commented
Had a quick look offline with Lars and we decided on different error handling. Will re-request review soon.

2021-04-30 21:39 UTC, lfrancke requested changes

2021-04-30 21:39 UTC, lfrancke commented on crd/src/lib.rs
> +pub const FINALIZER_NAME: &str = "zookeeper.stackable.tech/cleanup";
I think the name of a finalizer should be an implementation detail of the operator in question and doesn't belong here.

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +/// Contains all necessary information to configure a connection with this
`this` is a bit misleading in this case as there's no reference to a ZooKeeper ensemble anywhere

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +/// Zookeeper instance
Zookeeper -> ZooKeeper

And instance sounds like a single thing. Ensemble is the term ZK uses.

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +pub struct ZookeeperConnectionInformation {
Let's do it consistently at least.
Either name this ZooKeeperXYZ or rename all instances

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +#[allow(dead_code)]
Is this really needed?
My clippy doesn't complain about this (and also not the other one)
But I don't really trust clippy so....

2021-04-30 21:39 UTC, lfrancke commented on crd/src/error.rs
> +pub type ZookeeperOperatorResult<T> = std::result::Result<T, Error>;
See comment in util. 
Either use ZooKeeper or make it consistent.

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +/// * `zk_name` - The name of the ZookeeperCluster cr
expand cr & ZK naming

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +/// * `zk_namespace` - The namespace this ZookeeperCluster cr is in, if not provided will
expand cr & ZK naming

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +#[allow(dead_code)]
see above

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +    let chroot = chroot.trim_start_matches('/');
In theory can't you do 

```let chroot = chroot.trim_start_matches('/').trim_end_matches('/');```

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +    }
This part is not chroot specific, no?
Could you move this to a `valid_node_name` method or something like that?

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +    let reserved_words = vec![".", "..", "zookeeper"];
Instead of creating this vec over and over can't you move this to a const RESERVED_WORDS: [&str; 3]?
(This'd be my first time using Arrays in Rust)

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +    // The value E000 in the list below does not exactly match what is written in the Zookeeper
I see....

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +            message: "string contained prohibited unicode characters".to_string(),
can we emit the character here?

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +        matches!(character,'\u{0000}'
```suggestion
        matches!(character, '\u{0000}'
```

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +    zk_namespace: Option<&str>,
ZK is always namespaced, there can be two clusters with the same name otherwise and this'd lead to wrong results checking for pods etc.

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +    zk_namespace: Option<&str>,
see above, always namespaced

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +    let zk_cluster = api.get(zk_name).await;
I believe you can just do

```
client.get(...)
``` 
instead of creating your own API

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +    // TODO: We need to watch the ZooKeeper resource and do _something_ when it goes down or when its nodes are changed
this is not valid here, copy & paste I think

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +// Builds the actual connection string after all necessary information has been retrieved.
To get the port you'd need to get the corresponding configmap, or we add a label with the port....

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +                    reference: "ERR_ZK_POD_WITHOUT_NAME".to_string(),
This is good but could those strings also be enum instead? (happy to merge as is though)

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +    server_and_port_list.sort_by(|(host1, _), (host2, _)| host1.cmp(host2));
I understand where you're coming from but there's something to be said about randomizing this as well as it might balance the load between the machines more evenly

2021-04-30 21:39 UTC, lfrancke commented on crd/src/util.rs
> +/// Returns connection information for a ZookeeperCluster custom resource
Could you add an example of what a connection string would look like? 
Doesn't have to be code, just text would be fine for me

2021-05-01 07:34 UTC, soenkeliebau commented on crd/src/util.rs
> +#[allow(dead_code)]
I got warnings when adding this and added it, but I have never tried again without in this state, will give it a try..

2021-05-01 07:37 UTC, soenkeliebau commented on crd/src/util.rs
> +pub struct ZookeeperConnectionInformation {
I didn't want to muddy this PR with that change, as that is a breaking one for users of this crate and felt that shouldn't be hidden away in something entirely unrelated.
But also didn't want to make it ZooKeeperxyz now in the knowledge that i'll change it again soon.
Ok to create a follow up PR to change it in the rest of the code?

2021-05-01 07:41 UTC, soenkeliebau commented on crd/src/util.rs
> +            message: "string contained prohibited unicode characters".to_string(),
We'd have to do the check in a different way for that, but possible of course.
Also, we'd probably have to not print the character itself but the codepoint as most of these don't really display well..

2021-05-01 07:41 UTC, soenkeliebau commented on crd/src/util.rs
> +    }
true, will move it

2021-05-01 07:43 UTC, soenkeliebau commented on crd/src/util.rs
> +                    reference: "ERR_ZK_POD_WITHOUT_NAME".to_string(),
Jup, that was something I wanted to discuss at some point, where to manage these. I think every operator should be in charge of these references for itself, we just need to ensure that we pull them together somewhere in the docs for searching.

2021-05-01 07:53 UTC, soenkeliebau commented on crd/src/util.rs
> +    server_and_port_list.sort_by(|(host1, _), (host2, _)| host1.cmp(host2));
My understanding is that he order of hosts in the string is irrelevant for which host is connected to:

https://zookeeper.apache.org/doc/current/apidocs/zookeeper-server/org/apache/zookeeper/ZooKeeper.html#ZooKeeper-java.lang.String-int-org.apache.zookeeper.Watcher-

2021-05-01 20:46 UTC, lfrancke requested changes

2021-05-01 20:46 UTC, lfrancke commented on crd/src/util.rs
> +    let _ = is_valid_node(chroot)?;
Do you need to assign?
Wouldn't this work as well

```suggestion
    is_valid_node(chroot)?;
```

2021-05-01 20:46 UTC, lfrancke commented on crd/src/util.rs
> +/// Check if the name is a valid nome for a znode in Zookeeper
```suggestion
/// Check if the name is a valid nome for a znode in ZooKeeper
```

2021-05-01 20:46 UTC, lfrancke commented on crd/src/util.rs
> +/// be a valid znode, but signify a nested structure
I don't understand this sentence

2021-05-01 20:46 UTC, lfrancke commented on crd/src/util.rs
> +// We may want to revisit this later depending on how exactly this code is used
Only // on purpose?

2021-05-03 13:16 UTC, lfrancke commented on crd/src/util.rs
> +pub struct ZookeeperConnectionInformation {
Okay. It'd be great if we could have that as an immediate follow-up. I'll put an issue in the backlog

2021-05-03 13:18 UTC, lfrancke commented on crd/src/util.rs
> +#[allow(dead_code)]
And what was the result?

2021-05-03 13:21 UTC, lfrancke commented on crd/src/util.rs
> +    server_and_port_list.sort_by(|(host1, _), (host2, _)| host1.cmp(host2));
Okay, good to know, yes.

2021-05-03 13:25 UTC, lfrancke requested changes
minor typos only

2021-05-03 13:25 UTC, lfrancke commented on crd/src/util.rs
> +    // https://zookeeper.apache.org/doc/r3.5.1-alpha/zookeeperProgrammers.html#ch_zkSessions
Can we use a non-alpha link here?

2021-05-03 13:25 UTC, lfrancke commented on crd/src/util.rs
> +/// * `chroot` - The chroot string which should be checked against ZooKeepers naming rules
```suggestion
/// * `chroot` - The chroot string which should be checked against ZooKeeper's naming rules
```

I'm not good at grammar, might be wrong

2021-05-03 13:25 UTC, lfrancke commented on crd/src/util.rs
> +/// * [`IllegalChroot`] if the name violates any of ZooKeepers naming rules
see above
```suggestion
/// * [`IllegalChroot`] if the name violates any of ZooKeeper's naming rules
```

2021-05-03 13:25 UTC, lfrancke commented on crd/src/util.rs
> +/// Check if the name is a valid nome for a znode in ZooHeeper
```suggestion
/// Check if the name is a valid name for a znode in ZooHeeper
```

2021-05-03 13:25 UTC, lfrancke commented on crd/src/util.rs
> +/// * [`IllegalChroot`] if the name violates any of ZooKeepers naming rules
```suggestion
/// * [`IllegalChroot`] if the name violates any of ZooKeeper's naming rules
```

2021-05-03 13:25 UTC, lfrancke commented on crd/src/util.rs
> +// Checks the string for any illegal characters according to ZooKeepers rules and returns
```suggestion
// Checks the string for any illegal characters according to ZooKeeper's rules and returns
```

2021-05-03 13:27 UTC, lfrancke commented on crd/src/util.rs
> +    // https://zookeeper.apache.org/doc/r3.5.1-alpha/zookeeperProgrammers.html#ch_zkSessions
https://zookeeper.apache.org/doc/r3.7.0/zookeeperProgrammers.html#ch_zkDataModel

2021-05-03 14:11 UTC, lfrancke requested changes
Two things left: URL and one open comment about the allow dead_code thing

2021-05-05 19:22 UTC, lfrancke requested changes
mostly typos, almost there!

2021-05-05 19:22 UTC, lfrancke commented on crd/src/util.rs
> +    let clean_chroot = pad_and_check_chroot(chroot)?;
This check is much cheaper than the list so I suggest moving it before the list to bail out as early as possible

2021-05-05 19:29 UTC, lfrancke commented on crd/src/util.rs
> +/// Contains all necessary information to configure a connection with this
"configure" sounds weird but yes, it's better.
Maybe "establish" or "create"?

2021-05-05 19:32 UTC, lfrancke commented on crd/src/util.rs
> +// Builds the actual connection string after all necessary information has been retrieved.
You are correct. Not sure why I thought so complicated

2021-05-05 20:12 UTC, soenkeliebau commented on crd/src/util.rs
> +/// Contains all necessary information to configure a connection with this
done

2021-05-05 20:12 UTC, soenkeliebau commented on crd/src/util.rs
> +///     of this parameter will be checked for validity according to ZooKeepers [naming rules for
done

2021-05-05 20:13 UTC, soenkeliebau commented on crd/src/util.rs
> +///     a / character. If this is the case the  slash at the beginning will be added.
done

2021-05-05 20:14 UTC, soenkeliebau commented on crd/src/util.rs
> +///     string being padded to the ZooKeeper root. Functionaly this does not make a difference when
padded with a slash "" -> "/"

I've changed the wording a bit

2021-05-05 20:16 UTC, soenkeliebau commented on crd/src/util.rs
> +    let clean_chroot = pad_and_check_chroot(chroot)?;
done

2021-05-05 21:03 UTC, lfrancke approved these changes

2021-05-05 21:21 UTC, merged